### ISSUE TITLE
Add a `pass` backend as alternative to the Linux keyring to retrieve the shibboleth credentials

### ISSUE THREAD

**Issue by Ma27** [FliegendeWurst/KIT-ILIAS-downloader#32]
Rather than using e.g. KWallet or gnome-keyring, I prefer to manage all my credentials with [`pass(1)`](https://www.passwordstore.org/).

I'm not aware of any integration between the freedesktop secret-manager standard and `pass`, also it doesn't seem so uncommon to provide different backends depending on where to retrieve credentials, see for instance how [aws-vault](https://github.com/99designs/aws-vault#vaulting-backends) does this. The primary downside of course would be the increased maintenance load.

The integration could basically look like this:

```
KIT-ILIAS-downloader --keyring
```

for using the system keyring or

```
KIT-ILIAS-downloader -U uXXXX --pass-prefix edu/kit/uXXXX
```

with `--pass-prefix` and `--keyring` being mutually exclusive.

Would you be open to accept such a change? If yes, I may take some time soonish(tm) and implement that :)

**Comment by FliegendeWurst** [comment]
I'd accept this new option. https://github.com/FliegendeWurst/KIT-ILIAS-downloader/blob/f21c0249ed971cda710d07be8af35e819eda7df9/src/cli.rs#L150 is probably a good starting point when implementing a new password backend.

> Rather than using e.g. KWallet or gnome-keyring

FWIW, I'm currently using the secret service integration included in KeepassXC (because it can be set up to require confirmation on each password access, unlike KWallet).
